### ISSUE TITLE
Add ability to duplicate a course in the courses table

### ISSUE THREAD

**Issue by WadeVaresio** [ucsb-cs156-s21/proj-ucsb-cs-las#194]
# User Story

As an admin I can duplicate an existing course so that I can easily create a new course by simply modifying some of the fields

# Discussion
Oftentimes courses are similar, i.e. same professor, same time, etc. that it is advantageous for users to be able to duplicate an already existing course and modify some of the fields to speed up the course creation process.

You may choose to split up this issue by splitting up the frontend and backend tasks.

# Acceptance Criteria

- [ ] There is a duplicate button for each course in the Courses page.
- [ ] Storybook correctly reflects the new column in the Courses page.
...

# Implementation Todos

Front end:

- [ ] Add a column to the Courses Table component, that contains a button to duplicate the course.
- [ ] Implement appropriate frontend tests.
...

Back end:

- [ ] Create an endpoint that given a course, duplicates the course and adds it to the appropriate repository
- [ ] Implement appropriate backend tests.
...

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage
...
